config/routes.rb
Rails.application.routes.draw do
  resources :keywords
  devise_for :users
  resources :posts
  #get 'home/index'
  get 'home/about'
  get 'home/keyword_posts'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   		has_many :posts
   		has_many :keywords
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  	@about_me = "My name is Hannah!"
  	@answer = 2 + 2
  end
  
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: %i[ show edit update destroy ]
  # GET /keywords or /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1 or /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords or /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: "Keyword was successfully created." }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1 or /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: "Keyword was successfully updated." }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1 or /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: "Keyword was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def keyword_params
      params.require(:keyword).permit(:key_word, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    #@post = Post.new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "Not Authorized To Edit This Post" if @post.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :item, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
	<%= link_to 'Daangn Market', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to "About Me", home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Write Post", new_post_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Keywords", keywords_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Posts Matching Keywords", home_keyword_posts_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>

        <% end %>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<br/>

app/views/home/about.html.erb
<h1>About me</h1>

<p>
	<% if @about_me.include? "Hannah" %>
		My name is Hannah!
	<% else %>
		My name is NOT Hannah.
	<% end %>
</p>

app/views/home/index.html.erb
<h1>hello world!</h1>
my first rails webpage :)

app/views/home/keyword_posts.html.erb
<% if user_signed_in? %>

  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Post Title</th>
        <th>Body</th>
        <th>Keyword</th>
      </tr>
    </thead>

    <tbody>
      <% Post.all.each do |post| %>
        <% Keyword.all.each do |keyword| %>
          <% if (keyword.user == current_user) && (post.user != current_user) && (post.body.include? keyword.key_word) %>

            <tr>
              <td>
                <%= link_to post.title + ' ' + post.item, post %>
              </td>
              <td><%= post.body %></td>
              <td><%= keyword.key_word %></td>
            </tr>

          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br/>
<% end %>

app/views/keywords/_form.html.erb
<%= form_with(model: keyword) do |form| %>
  <% if keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
        <% keyword.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :key_word, class:"form-control", placeholder:"Keyword" %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :post_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h4>My Keywords</h4>
<br/>
<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <% if keyword.user == current_user %>
        <tr>
          <td><b><%= keyword.key_word %></b></td>
          <td><%= link_to 'Show', keyword, class:"btn btn-secondary" %></td>
          <td><%= link_to 'Edit', edit_keyword_path(keyword), class:"btn btn-secondary" %></td>
          <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path, class:"btn btn-secondary" %>

app/views/keywords/new.html.erb
<h4>Add a New Keyword</h4>
<br/>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key word:</strong>
  <%= @keyword.key_word %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Daangn App</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">

      <% if notice %>
        <br/>
        <%= render 'layouts/alerts' %>
      <% end %>

    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :item, class:"form-control", placeholder:"Item" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :body, class:"form-control", placeholder:"Body" %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :post_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<br/>

<%= render 'form', post: @post %>

<br/>
<%= link_to 'Show', @post, class:"btn btn-secondary" %>
<%= link_to 'Delete', @post,  method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<%= link_to 'Back', posts_path, class:"btn btn-dark" %>

app/views/posts/index.html.erb
<% if user_signed_in? %>

  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Post Title</th>
        <th>Body</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <%= link_to post.title + ' ' + post.item, post %>
          </td>
          <td><%= post.body %></td>

          <td><%= link_to 'Delete', post,  method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-small btn-outline-danger" %></td>

        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path, class:"btn btn-outline-secondary" %>
<% else %>
  <h1>Hello World!</h1>
<% end %>

app/views/posts/new.html.erb
<h1>Write a Post</h1>
<br/>
<%= render 'form', post: @post %>

<br/>
<%= link_to 'Back', posts_path, class:"btn btn-secondary" %>

app/views/posts/show.html.erb
<div class="card text-dark bg-light mb-3" style="max-width: 190rem;">
  <div class="card-body">
    <h1 class="card-title"><%= @post.title %></h1>
    <h2 class="card-subtitle mb-2 text-muted"><%= @post.item %></h2>
    <p class="card-text"><%= @post.body %></p>
    <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-secondary" %>
    <%= link_to 'Delete', @post,  method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
	<%= link_to 'Back', posts_path, class:"btn btn-secondary" %>
  </div>
</div>